import SideBareCreate from "./sideBareCreate";
import MenuCreate from "./menu";
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return  <main className=" w-full h-full">
            <div className=' flex w-full h-screen'>
                <SideBareCreate />
                <MenuCreate />
                <div className=' w-full flex-1 md:flex bg-[#ededed] hidden'>
                    {children}
                </div>
            </div>
        </main>;
}